# permissions for end users to view replicatedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: replicatedsecret-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-replicator
    app.kubernetes.io/part-of: k8s-replicator
    app.kubernetes.io/managed-by: kustomize
  name: replicatedsecret-viewer-role
rules:
- apiGroups:
  - replicas.k8s.sh
  resources:
  - replicatedsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - replicas.k8s.sh
  resources:
  - replicatedsecrets/status
  verbs:
  - get
